// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG7fX7gXdmSqxLw7u1fyAYY7kaOwbATro',
    appId: '1:955836907761:web:271e17ec79f19f30bbe950',
    messagingSenderId: '955836907761',
    projectId: 'my-firebase-project-e0d19',
    authDomain: 'my-firebase-project-e0d19.firebaseapp.com',
    storageBucket: 'my-firebase-project-e0d19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCos4XGNay62HxHsszmdtVfzGrl--XLVhM',
    appId: '1:955836907761:android:1a48152e14a9546abbe950',
    messagingSenderId: '955836907761',
    projectId: 'my-firebase-project-e0d19',
    storageBucket: 'my-firebase-project-e0d19.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr6HA7g3VKsTTW1jGUjbAVKYP21oZ6EOE',
    appId: '1:955836907761:ios:16d4eb3e6d9a5292bbe950',
    messagingSenderId: '955836907761',
    projectId: 'my-firebase-project-e0d19',
    storageBucket: 'my-firebase-project-e0d19.appspot.com',
    androidClientId: '955836907761-ar25jd1o8q1vnu96um6d4dq2inl9lct0.apps.googleusercontent.com',
    iosClientId: '955836907761-blg5acbtskunjrupuprilm9jfif44gge.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginFirebase',
  );

}